with-expecter: True
dir: "{{.InterfaceDirRelative}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}_mocks"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/bitmagnet-io/bitmagnet/internal/classifier:
    interfaces:
      LocalSearch:
  github.com/bitmagnet-io/bitmagnet/internal/protocol/dht/ktable:
    interfaces:
      Table:
  github.com/bitmagnet-io/bitmagnet/internal/protocol/dht/responder:
    interfaces:
      Limiter:
  github.com/bitmagnet-io/bitmagnet/internal/tmdb:
    interfaces:
      Client:
  github.com/bitmagnet-io/bitmagnet/internal/llm:
    interfaces:
      Client:
  github.com/bitmagnet-io/bitmagnet/internal/porndb:
    interfaces:
      Client:
  github.com/bitmagnet-io/bitmagnet/internal/stashdb:
    interfaces:
      Client:
  github.com/bitmagnet-io/bitmagnet/internal/musicbrainz:
    interfaces:
      Client:
  github.com/bitmagnet-io/bitmagnet/internal/openlibrary:
    interfaces:
      Client:
  github.com/bitmagnet-io/bitmagnet/internal/comicvine:
    interfaces:
      Client:
  github.com/bitmagnet-io/bitmagnet/internal/torznab:
    interfaces:
      Client:
