type DhtStats {
  nodesCountIPv4: Int!
  nodesCountIPv6: Int!
  hashesCountIPv4: Int!
  hashesCountIPv6: Int!
  serverStartTime: DateTime
  serverLastSuccess: DateTime
  serverLastResponse: DateTime
  crawlerActive: Boolean!
}

type DhtSnapshot {
  bucket: DateTime!
  nodesIPv4: Int!
  nodesIPv6: Int!
  hashesIPv4: Int!
  hashesIPv6: Int!
}

type DhtMetricsResult {
  snapshots: [DhtSnapshot!]!
}

input DhtMetricsInput {
  bucketDuration: MetricsBucketDuration!
  startTime: DateTime
  endTime: DateTime
}

type DhtQuery {
  stats: DhtStats!
  metrics(input: DhtMetricsInput!): DhtMetricsResult!
}
