// Code generated by mockery v2.53.6. DO NOT EDIT.

package comicvine_mocks

import (
	context "context"

	comicvine "github.com/bitmagnet-io/bitmagnet/internal/comicvine"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// SearchVolumes provides a mock function with given fields: ctx, req
func (_m *Client) SearchVolumes(ctx context.Context, req comicvine.SearchVolumesRequest) (comicvine.SearchVolumesResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchVolumes")
	}

	var r0 comicvine.SearchVolumesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, comicvine.SearchVolumesRequest) (comicvine.SearchVolumesResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, comicvine.SearchVolumesRequest) comicvine.SearchVolumesResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(comicvine.SearchVolumesResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, comicvine.SearchVolumesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_SearchVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchVolumes'
type Client_SearchVolumes_Call struct {
	*mock.Call
}

// SearchVolumes is a helper method to define mock.On call
//   - ctx context.Context
//   - req comicvine.SearchVolumesRequest
func (_e *Client_Expecter) SearchVolumes(ctx interface{}, req interface{}) *Client_SearchVolumes_Call {
	return &Client_SearchVolumes_Call{Call: _e.mock.On("SearchVolumes", ctx, req)}
}

func (_c *Client_SearchVolumes_Call) Run(run func(ctx context.Context, req comicvine.SearchVolumesRequest)) *Client_SearchVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(comicvine.SearchVolumesRequest))
	})
	return _c
}

func (_c *Client_SearchVolumes_Call) Return(_a0 comicvine.SearchVolumesResponse, _a1 error) *Client_SearchVolumes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_SearchVolumes_Call) RunAndReturn(run func(context.Context, comicvine.SearchVolumesRequest) (comicvine.SearchVolumesResponse, error)) *Client_SearchVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
