// Code generated by mockery v2.53.6. DO NOT EDIT.

package llm_mocks

import (
	context "context"

	llm "github.com/bitmagnet-io/bitmagnet/internal/llm"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function with given fields: ctx, input
func (_m *Client) Classify(ctx context.Context, input llm.ClassifyInput) (llm.ClassifyResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 llm.ClassifyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, llm.ClassifyInput) (llm.ClassifyResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, llm.ClassifyInput) llm.ClassifyResult); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(llm.ClassifyResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, llm.ClassifyInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type Client_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - input llm.ClassifyInput
func (_e *Client_Expecter) Classify(ctx interface{}, input interface{}) *Client_Classify_Call {
	return &Client_Classify_Call{Call: _e.mock.On("Classify", ctx, input)}
}

func (_c *Client_Classify_Call) Run(run func(ctx context.Context, input llm.ClassifyInput)) *Client_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(llm.ClassifyInput))
	})
	return _c
}

func (_c *Client_Classify_Call) Return(_a0 llm.ClassifyResult, _a1 error) *Client_Classify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_Classify_Call) RunAndReturn(run func(context.Context, llm.ClassifyInput) (llm.ClassifyResult, error)) *Client_Classify_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
