// Code generated by mockery v2.53.6. DO NOT EDIT.

package porndb_mocks

import (
	context "context"

	porndb "github.com/bitmagnet-io/bitmagnet/internal/porndb"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// SearchJAV provides a mock function with given fields: ctx, req
func (_m *Client) SearchJAV(ctx context.Context, req porndb.SearchJAVRequest) (porndb.SearchJAVResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchJAV")
	}

	var r0 porndb.SearchJAVResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, porndb.SearchJAVRequest) (porndb.SearchJAVResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, porndb.SearchJAVRequest) porndb.SearchJAVResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(porndb.SearchJAVResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, porndb.SearchJAVRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_SearchJAV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchJAV'
type Client_SearchJAV_Call struct {
	*mock.Call
}

// SearchJAV is a helper method to define mock.On call
//   - ctx context.Context
//   - req porndb.SearchJAVRequest
func (_e *Client_Expecter) SearchJAV(ctx interface{}, req interface{}) *Client_SearchJAV_Call {
	return &Client_SearchJAV_Call{Call: _e.mock.On("SearchJAV", ctx, req)}
}

func (_c *Client_SearchJAV_Call) Run(run func(ctx context.Context, req porndb.SearchJAVRequest)) *Client_SearchJAV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(porndb.SearchJAVRequest))
	})
	return _c
}

func (_c *Client_SearchJAV_Call) Return(_a0 porndb.SearchJAVResponse, _a1 error) *Client_SearchJAV_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_SearchJAV_Call) RunAndReturn(run func(context.Context, porndb.SearchJAVRequest) (porndb.SearchJAVResponse, error)) *Client_SearchJAV_Call {
	_c.Call.Return(run)
	return _c
}

// SearchScenes provides a mock function with given fields: ctx, req
func (_m *Client) SearchScenes(ctx context.Context, req porndb.SearchScenesRequest) (porndb.SearchScenesResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchScenes")
	}

	var r0 porndb.SearchScenesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, porndb.SearchScenesRequest) (porndb.SearchScenesResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, porndb.SearchScenesRequest) porndb.SearchScenesResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(porndb.SearchScenesResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, porndb.SearchScenesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_SearchScenes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchScenes'
type Client_SearchScenes_Call struct {
	*mock.Call
}

// SearchScenes is a helper method to define mock.On call
//   - ctx context.Context
//   - req porndb.SearchScenesRequest
func (_e *Client_Expecter) SearchScenes(ctx interface{}, req interface{}) *Client_SearchScenes_Call {
	return &Client_SearchScenes_Call{Call: _e.mock.On("SearchScenes", ctx, req)}
}

func (_c *Client_SearchScenes_Call) Run(run func(ctx context.Context, req porndb.SearchScenesRequest)) *Client_SearchScenes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(porndb.SearchScenesRequest))
	})
	return _c
}

func (_c *Client_SearchScenes_Call) Return(_a0 porndb.SearchScenesResponse, _a1 error) *Client_SearchScenes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_SearchScenes_Call) RunAndReturn(run func(context.Context, porndb.SearchScenesRequest) (porndb.SearchScenesResponse, error)) *Client_SearchScenes_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
