// Code generated by mockery v2.53.6. DO NOT EDIT.

package musicbrainz_mocks

import (
	context "context"

	musicbrainz "github.com/bitmagnet-io/bitmagnet/internal/musicbrainz"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// SearchRelease provides a mock function with given fields: ctx, req
func (_m *Client) SearchRelease(ctx context.Context, req musicbrainz.SearchReleaseRequest) (musicbrainz.SearchReleaseResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchRelease")
	}

	var r0 musicbrainz.SearchReleaseResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, musicbrainz.SearchReleaseRequest) (musicbrainz.SearchReleaseResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, musicbrainz.SearchReleaseRequest) musicbrainz.SearchReleaseResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(musicbrainz.SearchReleaseResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, musicbrainz.SearchReleaseRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_SearchRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchRelease'
type Client_SearchRelease_Call struct {
	*mock.Call
}

// SearchRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - req musicbrainz.SearchReleaseRequest
func (_e *Client_Expecter) SearchRelease(ctx interface{}, req interface{}) *Client_SearchRelease_Call {
	return &Client_SearchRelease_Call{Call: _e.mock.On("SearchRelease", ctx, req)}
}

func (_c *Client_SearchRelease_Call) Run(run func(ctx context.Context, req musicbrainz.SearchReleaseRequest)) *Client_SearchRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(musicbrainz.SearchReleaseRequest))
	})
	return _c
}

func (_c *Client_SearchRelease_Call) Return(_a0 musicbrainz.SearchReleaseResponse, _a1 error) *Client_SearchRelease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_SearchRelease_Call) RunAndReturn(run func(context.Context, musicbrainz.SearchReleaseRequest) (musicbrainz.SearchReleaseResponse, error)) *Client_SearchRelease_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
